### ISSUE TITLE
This addon parses node_modules

### ISSUE THREAD

**Issue by sir-dunxalot** [dockyard/ember-suave#67] opened 2015-10-03 03:12 UTC
After running `ember install ember-suave` in an addon and booting the server, the node modules folder is parsed by JSCS.

The [default JSCS options]((https://github.com/jscs-dev/node-jscs/blob/master/lib/config/configuration.js#L117)) includes an `excludeFiles` hash. However, this addon does not. The JSCS default is:

```json
{
  "excludeFiles": [".git/**", "node_modules/**"]
}
```

Adding this to the project's `.jscsrc` still didn't stop parsing the `node_modules` folder. Curiously I was seeing messages like the following:

![image](https://cloud.githubusercontent.com/assets/4495352/10261201/44911f10-695a-11e5-870d-400e73709642.png)

Liquid fire is a dependency of the project `ember-suave is installed in`. The project in question is an addon, not an app.

As such, adding `modules` to the list of excluded folders finally prevented parsing of the `node_modules` folder and the console only showed errors for code in my app.

```json
{
    "excludeFiles": [".git/**", "node_modules/**", "modules/**"]
}
```

1. Is parsing dependencies intended behaviour?
2. Is the need to add `modules` instead of `node_modules` a bug?

I'm happy to make a PR for issue 1 but would like to identify the core issue(s) first.

**Comment by buschtoens** [comment] 2015-10-07 20:20
I experience the same problem, however I don't think that `ember-suave` actually checks the `node_modules` directory.

JSCS only complains about the `node_modules/liquid-fire/addon/**` files, but names them as `modules/liquid-fire/**`.

`modules` probably is the virtual / temporary directory `ember-cli` / Babel uses for module lookup. I don't know if this only happens with `liquid-fire` but I only had it happen with that addon so far.

Your fix seems to be a valid solution, as it disables the checking for all "external" modules the user has no control over.

**Comment by shicholas** [comment] 2015-10-29 15:45
I can confirm both the error and your fix @sir-dunxalot, thanks

**Comment by brzpegasus** [comment] 2015-11-21 14:45
`ember-suave` doesn't parse the `node_modules` folder and the `"excludeFiles": [".git/**", "node_modules/**", "modules/**"]` configuration should normally be unnecessary (none of those folders are watched).

However, there is a [bug](https://github.com/ef4/liquid-fire/issues/383) in `liquid-fire` that causes what you're seeing. Version 0.21.3 in NPM has these extra lines in `liquid-fire/index.js`:

```js
  isDevelopingAddon: function() {
    return true;
  },
```

The 0.21.3 version on GitHub does not, however. I believe this was just mistakenly left in locally when the library was pushed to the NPM registry. We'll have to wait for a corrected version to be published, unfortunately (and continue to use the `excludeFiles` workaround in the meantime).

**Comment by rwjblue** [comment] 2015-11-21 15:26
@brzpegasus - Great spot! I think we can close this then...

**Closed** 2015-11-21 15:26 UTC
