### ISSUE TITLE
inconsistent error reporting

### ISSUE THREAD

**Issue by skaterdav85** [DockYard/ember-suave#97] opened 2015-12-17 22:41 UTC
Not sure if this is an ember-suave, JSCS, or my own issue, but I am noticing that the JSCS error reported are not always consistent. Sometimes it will report a handful of JSCS issues, I'll fix them so everything passes, and if I delete node_modules and reinstall ember-suave, it will report another set of JSCS errors. Has anyone experienced this?

Thanks!

**Comment by bcardarella** [comment] 2015-12-17 22:43
@skaterdav85 is it reporting on files in your application or on your deps?

**Comment by skaterdav85** [comment] 2015-12-17 22:55
anywhere in the application. i see it reporting issues in `/tests` or `/app`. I didn't do any configuration. I simply installed ember-suave. Do I need to modify `.jscsrc`? It seems like there is a caching issue. If I remove `node_modules/ember-suave`, the "cache" goes away and another set of errors come up.

**Comment by bcardarella** [comment] 2015-12-17 22:58
@skaterdav85 I actually think this is a broccoli caching issue. I recall @rwjblue telling me about this

**Comment by skaterdav85** [comment] 2015-12-17 23:59
thanks. i take it most people don't have this issue?

**Comment by jrowlingson** [comment] 2015-12-18 18:44
@skaterdav85 we are seeing this as well

**Comment by brzpegasus** [comment] 2015-12-18 18:52
When you remove `node_modules` and re-execute `npm install`, the following could happen:

* A new version of `ember-suave` could get installed (if the version specified in `package.json` is prefixed with `~

**Comment by brzpegasus** [comment] 2015-12-18 18:54
When you remove `node_modules` and re-execute `npm install`, the following could happen:

* A new version of `ember-suave` could get installed (if the version specified in `package.json` is prefixed with `~` or `^`
* A new version of `jscs` could get installed that fixes errors previously not caught, causing those errors to now be reported.

**Comment by skaterdav85** [comment] 2015-12-18 22:13
Thanks @brzpegasus. My team noticed this problem as I installed the addon, and they ran `npm install` and they were seeing JSCS errors when I had not. Any idea on what I can do to fix this?

**Comment by brzpegasus** [comment] 2015-12-18 22:20
Are you saying you have the same `ember-suave` and `jscs` versions as your team and are still getting a different output? (Check the versions of the packages actually installed in `node_modules`, not what's specified in `package.json`).

**Comment by rwjblue** [comment] 2015-12-19 03:00
Also would like to confirm that we are talking about the output of "ember test" being different, and *not* that the console emitted output is different. 

The console output being different is definitely possible and likely. We do not check every file upon every run (if file hasn't changed it isn't checked again) so it is likely that the console output would be different. 

Robert Jackson

-- twitter: rwjblue
-- github: rjackson

**Comment by jelhan** [comment] 2016-01-20 03:24
I have seen the same issue. I installed ember-suave to a lager project, which hadn't strict code style yet. Had a lot of errors of course. Fixed them until `ember test` did not reported any error anymore, committed and seen new errors reported by travis. I could not reproduce these errors locally. After deleting `/tmp`, `/dist`, `/node_modules` and `/bower_components`, reinstalling everything I got a new bunch of errors reported. I had this procedure a few times now.

I compared two travis logs for different commits. It seems like ember-suave (or jscs) stops testing after some amount of errors and all later tests just pass. There were a bunch of files tests passed for while having errors (which did not got reported before fixing the errors before). Together with a caching issue this would explain what's happening.

**Comment by jelhan** [comment] 2016-01-28 10:45
As @skaterdav85 already mentioned deleting `node_modules/ember-suave` is enough to clean cache. Of course you have to run `npm install` afterwards.

**Comment by jherdman** [comment] 2016-02-24 13:43
We see this on my team as well. We're integrating ember-suave into our project right now. I'll do a few test runs locally to identify, and fix, some issues, and then push up my changes only to have CI report a new batch of JSCS woes that weren't reported on my local test runs. This happens regardless of using `ember test` or `npm test` (obviously).

**Comment by brzpegasus** [comment] 2016-02-24 15:11
@jherdman This one has been hard to track down.

> I'll do a few test runs locally to identify, and fix, some issues, and then push up my changes only to have CI report a new batch of JSCS woes that weren't reported on my local test runs.

Are you saying that, after fixing the reported JSCS errors, `ember test` ran fine for you locally, but Travis would report new errors? And if so, what would make your local environment start reporting the same errors that Travis is seeing? By removing `tmp` and running `ember test` again?

**Comment by jherdman** [comment] 2016-02-24 15:12
> Are you saying that, after fixing the reported JSCS errors, ember test ran fine for you locally, but Travis would report new errors? 

Correct.

> By removing tmp and running ember test again?

If only! Sometimes yes, sometimes no. I found myself in a pattern of fixing what would be reported on CI, having a green run locally, pushing to CI and finding new errors.

**Comment by jelhan** [comment] 2016-02-25 14:35
> And if so, what would make your local environment start reporting the same errors that Travis is seeing? By removing tmp and running ember test again?

I had the same problem and - as said above - only deleting `node_modules/ember-suave` and running `npm install` was reliable.

**Comment by brzpegasus** [comment] 2016-02-26 15:39
Ok, so the good news is, one of our fellow DockYarders just encountered this issue, which gives me something more concrete to work with and debug, since I have access to the same project (and his local environment, if needed). Really hoping to get to the bottom of this soon!

**Comment by simonihmig** [comment] 2016-03-07 16:58
Same here, `ember test` was all passing, but Travis found additional errors. Just deleting `node_modules/ember-suave` was not enough, I had to `rm -rf node_modules && npm install`. But maybe that's just because of npm v3's flat module structure...

After that I could reproduce the Travis result locally.

**Comment by spencer516** [comment] 2016-03-23 00:20
Just want to throw this out there: I was running into this and discovered that jscs [sets the default `maxErrors` to 50](https://github.com/jscs-dev/node-jscs/blob/19764a040154110d939beaab6d3cfd2f7dc83dfb/lib/config/configuration.js#L8). I'd fix all of those and JSCS would no longer report any errors — but, I'm guessing that the Broccoli cache was not causing the files beyond the limit of 50 errors to be reprocessed. Still not totally sure this is the cause as I haven't dug too deep, but I hadn't seen anyone mention this as a possibility and seems like a good candidate. :)

**Comment by denchen** [comment] 2016-06-06 22:56
I just encountered this issue as well. After installing `ember-suave` and running `ember test`, I fixed a bunch of issues in my local environment and then pushed to my CI pipeline, which uncovered a bunch of other errors that weren't reported in the first place. When I deleted `/tmp`, `/dist`, and `/node_modules/` and reran `npm install`, I thus see those errors my CI pipeline reported.

I hope the workaround is not to constantly delete `node_modules` and re-install!

**Comment by spencer516** [comment] 2016-06-07 02:16
Just to update -- increasing the max number of errors did in fact resolve this for me. @denchen -- you may want to give that a try. (It's in part due to the Broccoli cache and that setting causing the weird behavior...deleting /tmp is probably sufficient to see more errors appear, rather than reinstalling)

**Comment by denchen** [comment] 2016-06-07 02:46
@spencer516 Hi Spencer, that seemed to work, but now my question is, is the `maxErrors` value a cumulative total? Does it get reset once I fix errors? If I set it at 1000, and I end up making 3-5 code style errors here and there and immediately fix them, will I still eventually hit the 1000 limit?

**Comment by brzpegasus** [comment] 2016-06-07 06:47
@denchen Can you see if the issue clears up when you set `maxErrors` to `null` rather than a number? Setting it to `null` is supposed to force all errors to be reported.

**Comment by denchen** [comment] 2016-06-09 04:04
@brzpegasus Hi, setting to `null` **appears** to resolve my issues. I'll have to continue using JSCS over an extended period of time to validate, but for now, I think everything is in working order. Thanks!

**Comment by brzpegasus** [comment] 2016-06-11 15:01
`maxErrors: null` has been added to the default [config](https://github.com/DockYard/ember-suave/blob/master/lib/jscsrc.json#L116). Going to close this issue, though please do reopen if the issue persists.

**Closed by brzpegasus** 2016-06-11 15:01 UTC
